<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Lists function --CGKAS_MPL_BTT</name>
   <tag></tag>
   <elementGuidId>54f772a2-4b65-4dd9-84e5-c2cdddc3aca5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sel_func_emp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sel_func_emp</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sel_func_emp</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Lists function --CGKAS_MPL_BTTCGKAS_MPL_LMCGKAS_MPL_LST_WSTCGKAS_MPL_MARSHALLCGKAS_MPL_RAMPCGKAS_MPL_TR_RAMPCGKAS_MPL_WINGMANCGKEQP_CBLCGKGSE_AMCGKGSE_APBCGKGSE_ASPV_ATNCGKGSE_ASPV_ATWCGKGSE_ASPV_BTTCGKGSE_ASPV_BTT_CGOCGKGSE_ASPV_HLLCGKGSE_ASUCGKGSE_ATNCGKGSE_ATWCGKGSE_BTTCGKGSE_BTT_CGOCGKGSE_GL_BTT_CGOCGKGSE_GPU_ACUCGKGSE_JL_ATWCGKGSE_JL_BTTCGKGSE_JL_GPUCGKGSE_JL_LLDCGKGSE_JL_MSLCGKGSE_KE_ATWCGKGSE_KE_BTTCGKGSE_KE_LLDCGKGSE_KE_MSLCGKGSE_KE_PBSCGKGSE_LLD_IPLCGKGSE_LSTCGKGSE_MSLCGKGSE_PBSCGKGSE_SPV_ATNCGKGSE_SPV_ATWCGKGSE_SPV_BTTCGKGSE_SPV_BTT_CGOCGKGSE_SPV_HLLCGKGSE_SPV_LSTWSTCGKGSE_WINGMANCGKGSE_WSTCGKOPS_ASPV_LCCGKOPS_ASPV_LMCGKOPS_ASPV_RAMPCGKOPS_GL_LMCGKOPS_GL_RAMPCGKOPS_LCCGKOPS_LM_JUNCGKOPS_LM_NCCGKOPS_LM_SR1CGKOPS_LM_SR2CGKOPS_LM_SR3CGKOPS_LM_SR4CGKOPS_MPLCGKOPS_RAMP_NCCGKOPS_RAMP_SR1CGKOPS_RAMP_SR2CGKOPS_RAMP_SR3CGKOPS_SPV_LCCGKOPS_SPV_LMCGKOPS_SPV_RAMPCGKPB_AMCGKPB_BI_AC_ASTCGKPB_BI_AOCGKPB_BI_ASPVCGKPB_BI_CKICGKPB_BI_CKIEDITCGKPB_BI_DUTY_OFCCGKPB_BI_FC_CKICGKPB_BI_GTECGKPB_BI_GTEDITCGKPB_BI_SPVCGKPB_BI_STBYCGKPB_BOCGKPB_CA_AC_ASTCGKPB_CA_CKICGKPB_CA_CKIEDITCGKPB_CA_CTLRCGKPB_CA_FC_CKICGKPB_CA_GTECGKPB_CA_SPVCGKPB_CI_AC_ASTCGKPB_CI_AOCGKPB_CI_CKICGKPB_CI_CKI2CGKPB_CI_CKIEDITCGKPB_CI_CTLRCGKPB_CICZ_CKICGKPB_CICZTG_ASPVCKICGKPB_CICZTG_ASPVGTECGKPB_CICZTG_GTECGKPB_CICZTG_SPVCGKPB_CICZTG_SPVCKICGKPB_CICZTG_SPVGTECGKPB_CI_DOORCGKPB_CI_FC_CKICGKPB_CI_GTECGKPB_CI_SPVCGKPB_CZ_AC_ASTCGKPB_CZ_AOCGKPB_CZCI_CKICGKPB_CZ_CKICGKPB_CZ_CKIEDITCGKPB_CZ_FC_CKICGKPB_CZ_GTECGKPB_CZ_SPVCGKPB_ET_AC_ASTCGKPB_ET_CI_GTECGKPB_ET_CKICGKPB_ET_FC_CKICGKPB_ET_GTECGKPB_ET_KE_GTECGKPB_ET_KLCZ_GTECGKPB_ET_MF_GTECGKPB_ET_MFVN_GTECGKPB_ET_TKTCGKPB_ET_VNKL_GTECGKPB_GA_ANNOUNCERCGKPB_GA_ASPV_DOMCKICGKPB_GA_ASPV_DOMGTECGKPB_GA_ASPV_INTCKICGKPB_GA_ASPV_INTGTECGKPB_GA_ASPV_PREMCGKPB_GA_CASHIERCGKPB_GA_DOCPROCCGKPB_GA_DOM_CKICGKPB_GA_DOM_CONNECTCGKPB_GA_DOM_CORIDORCGKPB_GA_DOM_GTECGKPB_GA_DOM_GTE_SYSCGKPB_GA_DOM_HDESKCGKPB_GA_DOM_PIC_GTECGKPB_GA_DOM_PREMCGKPB_GA_DOMPREM_SENCGKPB_GA_DOM_SEN_CKICGKPB_GA_GENDECCGKPB_GA_INT_CKICGKPB_GA_INT_CORIDORCGKPB_GA_INT_GTECGKPB_GA_INT_GTE_SYSCGKPB_GA_INT_HDESKCGKPB_GA_INT_PIC_GTECGKPB_GA_INT_PREMCGKPB_GA_INT_SEN_CKICGKPB_GA_INT_SENPREMCGKPB_GA_MARSHALCGKPB_GA_PIC_CASHIERCGKPB_GA_SEN_TD2CGKPB_GA_SPV_DOM_CKICGKPB_GA_SPV_DOM_GTECGKPB_GA_SPV_INT_CKICGKPB_GA_SPV_INT_GTECGKPB_GA_SPV_PREMCGKPB_GA_TD2CGKPB_INTPR_JAPANESECGKPB_INTPR_KOREANCGKPB_INTPR_MANDARINCGKPB_JL_AC_ASTCGKPB_JL_AOCGKPB_JL_ASPVCGKPB_JL_CKICGKPB_JL_CKI_ACCGKPB_JL_DOORCGKPB_JL_EDIT_S21CGKPB_JL_EDIT_S22CGKPB_JL_FC_CKICGKPB_JL_GTECGKPB_JL_SPVCGKPB_KE_AC_ASTCGKPB_KE_AOCGKPB_KE_ASPVCGKPB_KE_CASHIERCGKPB_KE_CKICGKPB_KE_CKI2CGKPB_KE_CKIEDITCGKPB_KE_CZ_AC_ASTCGKPB_KE_CZ_ASPV_GTECGKPB_KE_CZ_GTECGKPB_KE_CZ_SPV_GTECGKPB_KE_DUTY_OFCCGKPB_KE_FC_CKICGKPB_KE_FREIGHTCGKPB_KE_GTECGKPB_KE_SPVCGKPB_KL_AC_ASTCGKPB_KL_CKICGKPB_KL_CTLRCGKPB_KL_EDITCGKPB_KL_FC_CKICGKPB_KL_GTECGKPB_KL_GTE2CGKPB_KL_KE_CKICGKPB_KL_KE_GTECGKPB_KL_TKTCGKPB_KL_UL_CKICGKPB_KL_UL_FC_CKICGKPB_KL_UL_GTECGKPB_MF_SPVCGKPB_MFVN_AC_ASTCGKPB_MFVNCA_AOCGKPB_MFVNCA_SPVCGKPB_MFVN_CKICGKPB_MFVN_FC_CKICGKPB_MFVN_GTECGKPB_MPA_2YCGKPB_MPA_BI_GTECGKPB_MPA_CA_GTECGKPB_MPA_CASHIERCGKPB_MPA_CI_GTECGKPB_MPA_CZ_GTECGKPB_MPA_FLORWALKERCGKPB_MPA_JL_GTECGKPB_MPA_KE_GTECGKPB_MPA_LL_ADMCGKPB_MPA_LL_ASPVCGKPB_MPA_LL_BAG_SCHCGKPB_MPA_LL_CSCGKPB_MPA_LL_SPVCGKPB_MPA_MFVN_CKICGKPB_MPA_MFVN_GTECGKPB_MPA_TG_GTECGKPB_MPA_TR_GTECGKPB_MPA_UL_GTECGKPB_QG_ASPVCGKPB_QG_CKICGKPB_QG_CKI_INTCGKPB_QG_CKI_JEDCGKPB_QG_DOC_INTCGKPB_QG_GL_CKICGKPB_QG_GL_GTECGKPB_QG_GL_LLCGKPB_QG_GTECGKPB_QG_GTE_INTCGKPB_QG_GTE_JEDCGKPB_QG_GTE_SENCGKPB_QG_GTE_SYSCGKPB_QG_HDESKCGKPB_QG_LLCGKPB_QG_SPV_ASCGKPB_QG_SPV_PBHCGKPB_QG_TDCGKPB_QG_WTCGKPB_SJ_CKICGKPB_SJ_GTECGKPB_TG_AC_ASTCGKPB_TG_AOCGKPB_TG_CKICGKPB_TG_CTLRCGKPB_TG_EDITCGKPB_TG_FC_CKICGKPB_TG_GTECGKPB_TG_SPVCGKPB_TR_XN_CKI_GTECGKPB_TR_XN_FLT_SPVCGKPB_TR_XN_GLCGKPB_TR_XN_LLCGKPB_UL_AC_ASTCGKPB_UL_AOCGKPB_UL_ASPVCGKPB_UL_CKICGKPB_UL_CKI2CGKPB_UL_CKIEDITCGKPB_UL_DUTY_OFCCGKPB_UL_FC_CKICGKPB_UL_GTECGKPB_UL_GTE2CGKPB_UL_SPVCGKPB_VN_SPVCGKPB_XT_CKICGKPB_XT_GTECGKPB_XT_XN_CKI_GTECGKPB_XT_XN_GLCGKPB_XT_XN_PICTESTES1234TESTINGGTRY</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sel_func_emp&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='sel_func_emp']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//form[@id='frm_add_det']/div/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Function Name'])[2]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date'])[2]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End Date'])[2]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[4]/div/div/form/div/div/select</value>
   </webElementXpaths>
</WebElementEntity>
